# Generated by Django 4.2.1 on 2023-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('description', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advance')], default='Beginner', max_length=1)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
